# Generated by Django 4.0.3 on 2022-05-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_student_anonymous_id'),
        ('feedback', '0006_feedback_downvotes_feedback_upvotes_feedback_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotable', models.BooleanField(default=True)),
                ('downvotable', models.BooleanField(default=True)),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.feedback')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.student')),
            ],
        ),
    ]
